spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password: "password"
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        use_jdbc_metadata_defaults: false
  liquibase:
    enabled: true
    change-log: db.changelog-master.yaml

jwt:
  token:
    secret: "test_jwt_secret"
    expired: 3600000